set_property IOSTANDARD LVDS [get_ports DRP_CLK_IN_N]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list gtwizard_0_support_i/gt_usrclk_source/rxoutclk_mmcm1_i/gt0_rxusrclk2_out]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {gtwizard_0_support_i/gt0_rxdata_out[0]} {gtwizard_0_support_i/gt0_rxdata_out[1]} {gtwizard_0_support_i/gt0_rxdata_out[2]} {gtwizard_0_support_i/gt0_rxdata_out[3]} {gtwizard_0_support_i/gt0_rxdata_out[4]} {gtwizard_0_support_i/gt0_rxdata_out[5]} {gtwizard_0_support_i/gt0_rxdata_out[6]} {gtwizard_0_support_i/gt0_rxdata_out[7]} {gtwizard_0_support_i/gt0_rxdata_out[8]} {gtwizard_0_support_i/gt0_rxdata_out[9]} {gtwizard_0_support_i/gt0_rxdata_out[10]} {gtwizard_0_support_i/gt0_rxdata_out[11]} {gtwizard_0_support_i/gt0_rxdata_out[12]} {gtwizard_0_support_i/gt0_rxdata_out[13]} {gtwizard_0_support_i/gt0_rxdata_out[14]} {gtwizard_0_support_i/gt0_rxdata_out[15]} {gtwizard_0_support_i/gt0_rxdata_out[16]} {gtwizard_0_support_i/gt0_rxdata_out[17]} {gtwizard_0_support_i/gt0_rxdata_out[18]} {gtwizard_0_support_i/gt0_rxdata_out[19]} {gtwizard_0_support_i/gt0_rxdata_out[20]} {gtwizard_0_support_i/gt0_rxdata_out[21]} {gtwizard_0_support_i/gt0_rxdata_out[22]} {gtwizard_0_support_i/gt0_rxdata_out[23]} {gtwizard_0_support_i/gt0_rxdata_out[24]} {gtwizard_0_support_i/gt0_rxdata_out[25]} {gtwizard_0_support_i/gt0_rxdata_out[26]} {gtwizard_0_support_i/gt0_rxdata_out[27]} {gtwizard_0_support_i/gt0_rxdata_out[28]} {gtwizard_0_support_i/gt0_rxdata_out[29]} {gtwizard_0_support_i/gt0_rxdata_out[30]} {gtwizard_0_support_i/gt0_rxdata_out[31]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list gtwizard_0_support_i/gt_usrclk_source/gt0_txusrclk2_out]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list rxresetdone_vio_i]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 1 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list soft_reset_vio_i]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets gt0_txusrclk2_i]
