set_property SRC_FILE_INFO {cfile:C:/Vivado_Project/GTX_40M1280_20200627/GTX40M1280.srcs/constrs_1/new/top.xdc rfile:../../../GTX40M1280.srcs/constrs_1/new/top.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC J7 [get_ports  Q2_CLK1_GTREFCLK_PAD_N_IN ]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC J8 [get_ports  Q2_CLK1_GTREFCLK_PAD_P_IN ]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD12 [get_ports  DRP_CLK_IN_P]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD11 [get_ports  DRP_CLK_IN_N]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC K2 [get_ports TXP_OUT]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC K1 [get_ports TXN_OUT]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC K5 [get_ports RXN_IN]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC K6 [get_ports RXP_IN]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AB7 [get_ports reset]
