# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# IP: C:/Vivado_Project/GTX_40M1280_20200627/src/sources_1/ip/gtwizard_0/gtwizard_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gtwizard_0 || ORIG_REF_NAME==gtwizard_0} -quiet] -quiet

# XDC: c:/Vivado_Project/GTX_40M1280_20200627/src/sources_1/ip/gtwizard_0/gtwizard_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gtwizard_0 || ORIG_REF_NAME==gtwizard_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Vivado_Project/GTX_40M1280_20200627/src/sources_1/ip/gtwizard_0/gtwizard_0_ooc.xdc
