set_property SRC_FILE_INFO {cfile:c:/Lily_Zhang/GBS20V1/Elijah/git_repo/Xilinx_serdes_test_xpr/gtwizard_0_ex/gtwizard_0_ex.srcs/constrs_1/imports/example_design/gtwizard_0_exdes.xdc rfile:../../../gtwizard_0_ex.srcs/constrs_1/imports/example_design/gtwizard_0_exdes.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC U7 [get_ports  Q0_CLK1_GTREFCLK_PAD_N_IN ]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC U8 [get_ports  Q0_CLK1_GTREFCLK_PAD_P_IN ]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD12 [get_ports  DRP_CLK_IN_P]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC AD11 [get_ports  DRP_CLK_IN_N]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X0Y0 [get_cells gtwizard_0_support_i/gtwizard_0_init_i/inst/gtwizard_0_i/gt0_gtwizard_0_i/gtxe2_i]
